name: Execute

permissions:
  contents: write

on:
  schedule:
    - cron: "50 11 * * *"
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@master
        with:
          persist-credentials: false

      - name: Dependencies
        run: sudo apt install golang

      - name: Download data
        env:
          SECRET_EMAIL: ${{ secrets.SECRET_EMAIL }}
          SECRET_PASSWORD: ${{ secrets.SECRET_PASSWORD }}
        run: |
          TOKEN=$(curl -f --location \
              --request POST \
              'https://opendata.nationalrail.co.uk/authenticate' \
              --header 'Content-Type: application/x-www-form-urlencoded' \
              --data-urlencode "username=$SECRET_EMAIL" \
              --data-urlencode "password=$SECRET_PASSWORD" | jq -r .token)

          FNAME=$(curl --remote-name --remote-header-name \
              --write-out '%{filename_effective}' \
              --url 'https://opendata.nationalrail.co.uk/api/staticfeeds/2.0/fares' \
              --header 'content-type: application/x-www-form-urlencoded' \
              --header "x-auth-token: $TOKEN")
  
          echo ${FNAME%%.*} >> feedname
          cat feedname
          
          unzip "$FNAME"

      - name: Parse data
        run: |
          go mod download
          CGO_ENABLED=0 GOOS=linux go build -o railprice
          railprice "$(<feedname)"
